### ISSUE TITLE
Unsupported API version on 1.15.2

### ISSUE THREAD

**Issue by Bloodlex** [Xericore/EasyCarts#13]
[05:35:49] [Server thread/ERROR]: Could not load 'plugins/EasyCarts-2.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
	at org.bukkit.craftbukkit.v1_15_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:276) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:397) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:305) ~[patched_1.15.2.jar:git-Paper-385]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:360) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:234) ~[patched_1.15.2.jar:git-Paper-385]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:909) ~[patched_1.15.2.jar:git-Paper-385]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]

**Comment by Xericore** [comment]
Thanks for the hint. I've just released EasyCarts 2.1 that fixes this issue.
https://www.spigotmc.org/resources/easycarts.3941/
