### ISSUE TITLE
Does not work with 1.9.4

### ISSUE THREAD

**Issue by primis** [Xericore/EasyCarts#2]
[21:48:11 ERROR]: Could not load 'plugins/EasyCarts.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: com/github/xericore/easycarts/EasyCarts : Unsupported major.minor version 52.0
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[cb.jar:git-Spigot-8a048fe-042911f]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[cb.jar:git-Spigot-8a048fe-042911f]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [cb.jar:git-Spigot-8a048fe-042911f]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugins(CraftServer.java:297) [cb.jar:git-Spigot-8a048fe-042911f]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.reload(CraftServer.java:744) [cb.jar:git-Spigot-8a048fe-042911f]
        at org.bukkit.Bukkit.reload(Bukkit.java:539) [cb.jar:git-Spigot-8a048fe-042911f]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [cb.jar:git-Spigot-8a048fe-042911f]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [cb.jar:git-Spigot-8a048fe-042911f]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchCommand(CraftServer.java:646) [cb.jar:git-Spigot-8a048fe-042911f]
        at org.bukkit.craftbukkit.v1_9_R2.CraftServer.dispatchServerCommand(CraftServer.java:632) [cb.jar:git-Spigot-8a048fe-042911f]
        at net.minecraft.server.v1_9_R2.DedicatedServer.aL(DedicatedServer.java:437) [cb.jar:git-Spigot-8a048fe-042911f]
        at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:400) [cb.jar:git-Spigot-8a048fe-042911f]
        at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [cb.jar:git-Spigot-8a048fe-042911f]
        at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [cb.jar:git-Spigot-8a048fe-042911f]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_71]
Caused by: java.lang.UnsupportedClassVersionError: com/github/xericore/easycarts/EasyCarts : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_71]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800) ~[?:1.7.0_71]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.7.0_71]
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449) ~[?:1.7.0_71]
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71) ~[?:1.7.0_71]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361) ~[?:1.7.0_71]
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[?:1.7.0_71]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[cb.jar:git-Spigot-8a048fe-042911f]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[cb.jar:git-Spigot-8a048fe-042911f]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425) ~[?:1.7.0_71]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358) ~[?:1.7.0_71]
        at java.lang.Class.forName0(Native Method) ~[?:1.7.0_71]
        at java.lang.Class.forName(Class.java:274) ~[?:1.7.0_71]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[cb.jar:git-Spigot-8a048fe-042911f]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[cb.jar:git-Spigot-8a048fe-042911f]
        ... 14 more

**Comment by Xericore** [comment]
Strangely I didn't get an email notification about this issue. Thus I've seen it just now? Is this issue still open? Please let me know, if it is, I'll look into it.

**Comment by primis** [comment]
Still is open

**Comment by Xericore** [comment]
This error shows due to a mismatch between the Java version I compiled the plugin with and the Java version you are using to run the plugin. 
Which Java/JRE version are you running? I can't check which version I compiled with right now, but I believe it was Java 1.8. 
I'll have a look at this issue the next couple of days and compile a version that runs on as many JRE versions as possible.

**Comment by Xericore** [comment]
Please try the newest EasyCarts 1.8 available here in case this issue is still relevant for you. https://www.spigotmc.org/resources/easycarts.3941/
