### ISSUE TITLE
Error spamming

### ISSUE THREAD

**Issue by SpartanPride7** [Xericore/EasyCarts#7]
this error spams console

ERROR 04/06/2019 14:48:17
14:48:17Could not pass event PlayerInteractEvent to EasyCarts v1.12.2
Console 04/06/2019 14:48:17
14:48:17org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1337]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1337]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1337]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1337]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1337]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:236) ~[patched_1.12.2.jar:git-Paper-1337]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:203) ~[patched_1.12.2.jar:git-Paper-1337]
at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:199) ~[patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1510) ~[patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:24) ~[patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:5) ~[patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1337]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:426) [patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1337]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1337]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.ClassCastException

**Comment by Xericore** [comment]
This bug is a bit of a mystery to me. Try setting StopStartOnLeftClick to false. That should fix it.

**Comment by SpartanPride7** [comment]
I set it to false, reloaded the plugin, and the messages are still continuing

**Comment by SpartanPride7** [comment]
I had to delete the jar for now as the errors were happening multiple times a second and was lagging the server...let me know if you find anything!

**Comment by Xericore** [comment]
Sorry I don't have time to look into this in detail right now. Maybe next week.

**Comment by crazygmr101** [comment]
Did you ever figure this out? I was gonna check 1.14 support, and could look into this.

**Comment by Xericore** [comment]
I've just released EasyCarts 2.1 that fixes this issue.
https://www.spigotmc.org/resources/easycarts.3941/
